### ISSUE TITLE
`pycountry.countries.lookup()` returns lookup error for `'Russia'`, forces you to use `'Russian Federation'`

### ISSUE THREAD

**Issue by doriand01** [pycountry/pycountry#129]
Whenever I try using `pycountry.countries.lookup()` to lookup Russia, I get the following error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hassan2022cbtest/allpress/allpress/__init__.py", line 19, in add_country_to_db
    country = pycountry.countries.lookup(common_name)[0]
  File "/home/hassan2022cbtest/.local/lib/python3.9/site-packages/pycountry/db.py", line 39, in load_if_needed
    return f(self, *args, **kw)
  File "/home/hassan2022cbtest/.local/lib/python3.9/site-packages/pycountry/db.py", line 147, in lookup
    raise LookupError("Could not find a record for %r" % value)
LookupError: Could not find a record for 'russia'
```

But using `pycountry.countries.lookup('Russian Federation`) returns the country object. This should be fixed since the overwhelming majority of people refer to the Russian Federation by its common name of "Russia" and not as the "Russian Federation" in colloquial speech. `search_fuzzy()` solves this problem somewhat, but `search_fuzzy()` also has its own issues, such as returning incorrect results (for example, `search_fuzzy('Niger')` returns Nigeria as the top result.)

**Comment by TheMetaphorer** [comment]
The same bug exists when trying to do `pycountry.countries.lookup('Iran')`, you are forced to use `pycountry.countries.lookup('Islamic Republic of Iran')`

**Comment by TheMetaphorer** [comment]
Same bug also exists for Laos.

**Comment by TheMetaphorer** [comment]
Is there any intention to incorporate some of the functionality of country_converter into pycountry? Or would that be a redundancy?

**Comment by nschimmoller** [comment]
@TheMetaphorer I'd say for now I wouldn't expect this functionality to be added. I'm trying to work with the project maintainer to align on how we can distribute responsibility of maintaining current functionality across a team of contributors let alone building a roadmap of future development.

**Comment by adrianprochaska** [comment]
Recognized the same issues.
The easiest fix would probably be to add the names of **Iran, Russia and Laos** to the `common_name` attribute.
Venezuela has one of those:
```
>>> pycountry.countries.lookup('venezuela')
Country(alpha_2='VE', alpha_3='VEN', common_name='Venezuela', flag='🇻🇪', name='Venezuela, Bolivarian Republic of', numeric='862', official_name='Bolivarian Republic of Venezuela')
```

**Comment by nschimmoller** [comment]
This issue will likely be resolved by the combination of search_fuzzy use and the __getattr__ method incorporated in https://github.com/pycountry/pycountry/pull/134 

Attributes for the country class can be accessed using the `__getattr__` method. If the requested attribute is a key for the country class, it will return the corresponding value. In the special cases of missing 'common_name' or 'official_name' attributes, `__getattr__` will return 'name'. Here are some examples:

.. code:: pycon

  >>> aland = pycountry.countries.get(alpha_2='AX')

  >>> print(aland)
  Country(alpha_2='AX', alpha_3='ALA', flag='🇦🇽', name='Åland Islands', numeric='248')

  >>> aland.__getattr__('common_name')
  'Åland Islands'

  >>> aland.__getattr__('official_name')
  'Åland Islands'

  >>> aland.__getattr__('flag')
  '🇦🇽'

  >>> aland.__getattr__('')  # Raises AttributeError

**Comment by nschimmoller** [comment]
@doriand01 @adrianprochaska this has been release to main via #175 . Going to talk to maintainers about another PyPi release.

**Comment by apcamargo** [comment]
Is there a reason Russia, Laos, and Iran don't have the `common_name` field? Adding that would make `pycountry.countries.lookup()` more consistent, as people expect that it "just works" with common names.
