### ISSUE TITLE
GHA CI is not running unittests, unittests broken in master

### ISSUE THREAD

**Issue by Jamie-** [pycountry/pycountry#133]
It doesn't appear that your Github Actions CI is running your unittests. As a result of this, it appears that you have some unittests broken in master.

Running locally I see these failing:
* `test_currencies`
* `test_languages`
* `test_locales`
* `test_has_version_attribute`

**Comment by ctheune** [comment]
Yeah, this is definitely missing. We should be running this with a matrix build for the supported Python versions.

**Comment by zware** [comment]
Fixed in #140/ #164.
