### ISSUE TITLE
Support FIPS region codes

### ISSUE THREAD

**Issue by tobiasschuerg** [pycountry/pycountry#136]
It would be great if support for [FIPS region codes](https://en.wikipedia.org/wiki/List_of_FIPS_region_codes) would be added so that also those codes would be recognized.

A random example:
`PL-72`  is actually `PL-02`
See https://en.wikipedia.org/wiki/List_of_FIPS_region_codes_(P%E2%80%93R)#PL:_Poland and https://en.wikipedia.org/wiki/ISO_3166-2:PL.

This should be doably by a simple mapping table.

**Comment by nschimmoller** [comment]
@tobiasschuerg The intention of this library is to be a python wrapper for ISO Codes and unfortunately FIPS falls outside of that.  So this will definitely not make our development roadmap but if you'd like to submit a PR feel free :)
