### ISSUE TITLE
ISO 3166-1 Northern Ireland code is XI

### ISSUE THREAD

**Issue by maccer28** [pycountry/pycountry#137]
The code XI is being used by the [UK Government](https://en.wikipedia.org/wiki/UK_Government),[[25]](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#cite_note-25) as an [EORI number](https://en.wikipedia.org/wiki/EORI_number) country code prefix for [Northern Ireland](https://en.wikipedia.org/wiki/Northern_Ireland), and the members of [European union](https://en.wikipedia.org/wiki/European_union) for [European Union value added tax](https://en.wikipedia.org/wiki/European_Union_value_added_tax) reports with trade with [Northern Ireland](https://en.wikipedia.org/wiki/Northern_Ireland).[[26]](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#cite_note-26)

**Comment by theelous3** [comment]
This is just a bunch of wikipedia links, and one country doing something doesn't make it official anyway.

**Comment by maccer28** [comment]
https://taxation-customs.ec.europa.eu/system/files/2020-11/use_of_gb_and_xi_codes_guidance.pdf

**Comment by zware** [comment]
All data comes from the upstream [`iso-codes`](https://salsa.debian.org/iso-codes-team/iso-codes) project, we won't be making any changes for this here.
