### ISSUE TITLE
Missing former countries?

### ISSUE THREAD

**Issue by bohning** [pycountry/pycountry#152]
I have statistical data from FAO dating back to the year 1961 ([from here](https://www.fao.org/faostat/en/#data/QCL))

Both

- `pycountry.countries.get(numeric=str(area_code).zfill(3)).name` and
- `pycountry.historic_countries.get(numeric=str(area_code).zfill(3)).name`

fail for the following `area_codes` I see in the data:

- `058` --> `Belgium-Luxembourg`
- `230` --> `Ethiopia PDR`
- `736` --> `Sudan (former)`
- `890` --> `Yugoslav SFR`

All except the first one `058` I can find listed in the `withdrawn codes`of [ISO_3166-1_numeric](https://en.wikipedia.org/wiki/ISO_3166-1_numeric#Withdrawn_codes).

Oddly, I can’t find any reference on `058 Belgium-Luxembourg` anywhere except in the FAO data.

**Comment by zware** [comment]
All of `pycountry`'s ISO data comes directly from the Debian [`iso-codes` project](https://salsa.debian.org/iso-codes-team/iso-codes); any data issues should be taken up with that project.

**Comment by nschimmoller** [comment]
@bohning yesterday we released version 23.12.7 please update to that version using

`pip install pycountry --upgrade`

**Comment by bohning** [comment]
Thanks a lot!
