### ISSUE TITLE
Unusual characters in ISO 3166-2 Spanish subdivision data

### ISSUE THREAD

**Issue by megahall** [pycountry/pycountry#161]
Something looks a bit odd in the data for Spain:

From iso3166-2.json:

```
    {
      "code": "ES-A",
      "name": "Alacant*",
      "parent": "VC", 
      "type": "Province"
    }
```

**Comment by zware** [comment]
Odd though it be, it comes to us in the upstream data: https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/3832457204a22ea08d4b5f3668658e528ff84fef/data/iso_3166-2.json#L6244-6249

We won't be fixing that here, but please feel free to open an issue for it against the upstream project!
