### ISSUE TITLE
Country code in subdivision code breaks references between entries

### ISSUE THREAD

**Issue by JuroOravec** [pycountry/pycountry#17]
When a subdivision code already includes country code, and this subdivision is parent to another subdivision, the child stores the parent code as "{country_code}-{parent_code_with_country_code}", which leads to the reference being "{country_code}-{country_code}-{actual_parent_code}". However, such reference is nonsense and the parent subdivision cannot be obtained through it.

More info in #16. 

A workaround/future-proofing against such behavior can be [found in this branch](https://github.com/JuroOravec/pycountry/tree/fix/avoid-duplicate-country-code). Would it be good for PR?

**Comment by ctheune** [comment]
This should not have been an issue for a long time already and is covered by a unit test.

What's the specific example where this doesn't work?

**Comment by nschimmoller** [comment]
Code to reproduce:

``` python 
>>> [(i.code, i.parent_code) for i in pycountry.subdivisions if i.parent_code and not i.parent][:5]
[('GB-ABC', 'GB-GB-NIR'), ('GB-ABD', 'GB-GB-SCT'), ('GB-ABE', 'GB-GB-SCT'), ('GB-AGB', 'GB-GB-SCT'), ('GB-AGY', 'GB-GB-WLS')]
 sub = pycountry.subdivisions.get(code='GB-ABC')

>>> print(sub)
SubdivisionHierarchy(code='GB-ABC', country_code='GB', name='Armagh City, Banbridge and Craigavon', parent='GB-NIR', parent_code='GB-GB-NIR', type='District')
```
