### ISSUE TITLE
UserWarning raised when accessing `country.common_name`

### ISSUE THREAD

**Issue by terencehonles** [pycountry/pycountry#192]
It looks like `common_name` falls back to `name` as of https://github.com/pycountry/pycountry/pull/175.

Great! but I was already providing this fallback and now I'm getting a `UserWarning` when calling `hasattr(country, "common_name")`. `UserWarning` should only be raised if there is a different way I should be calling this code and I should update the code to fit this pattern. Falling back to `name` seems like it can just happen or if the fallback is not desired by default it should be a property with a different name (i.e. `common_name_or_name`).

I'll update my code to use this fallback, but there's no way I can get rid of this warning because *using* the fallback forces the warning.

**Comment by nschimmoller** [comment]
@terencehonles thanks for your feedback. 

User's designing a fallback method to use `name` when `common_name` or `official_name` was not found was a very common use case and as such made sense to add to the standard functionality of the package.

When designing for this functionality I wanted to avoid user's being misled on the existence of a `common_name` or `official_name` for a given country if it did not have one. I could easily see somebody creating an issue saying "`x` country does not have a `common_name` in `ISO3166-1.json` yet one was returned." I thought it best to inform users of what was occurring behind the scenes.

I can see the argument as well that perhaps you don't want it to return `name` and you want to know what countries are in fact missing a `common_name` or `official_name`. However, that does not seem to be your question / concern. 

> I'll update my code to use this fallback, but there's no way I can get rid of this warning because using the fallback forces the warning.

Could you maybe help me better understand your desired behavior? Does using the following code as a workaround solve your use case?

```python 
import warnings 
import re

warnings.filterwarning('ignore', category=UserWarning, message=re.escape("Country name provided instead"))

```

**Comment by zware** [comment]
TBH, I'm not particularly happy with the warning either.  I think we rushed this one a bit :(

I think a nicer design would have been to add a new API like `country.get_name()` with parameters to choose which name you prefer and which one(s) can be returned as fallbacks, no warning required.

**Comment by terencehonles** [comment]
> Could you maybe help me better understand your desired behavior? Does using the following code as a workaround solve your use case?
> 
> ```python
> import warnings 
> import re
> 
> warnings.filterwarning('ignore', category=UserWarning, message=re.escape("Country name provided instead"))
> ```

I'm very aware of this and it's not very good to be manually suppressing warnings like this. This would make sense if I couldn't fix the call so that it *wouldn't* warn, but since there's no call I can make other than:

```python
try:
    object.__getattribute__(country, "common_name")  # bypass pycountry's check
    return country.common_name
except AttributeError:
    return country.name
```

which will actually fix the warning (rather than tell pycountry to shut up), this really shouldn't be a warning.

I've already added the equivalent to this to the pytest config, but this is passing the burden to the user to update their config when there's not really anything that _can_ be changed to fix the warning.

**Comment by nschimmoller** [comment]
@terencehonles thanks for the input and feedback. I would like to confirm I understand your desired behavior, apologies if I misunderstand at all.

- Falling back to `name` when `common_name` or `official_name` is valuable functionality
- Implementing a method or attribute such as `get_name()` or `common_name_or_name` would be a better implementation than current state
- Use of `UserWarning` in `pycountry` should be limited to inform or guide a user to change their behavior and not to inform uses of internal behavior

Is that a fair summary?
