### ISSUE TITLE
countries.search_fuzzy() prints to terminal

### ISSUE THREAD

**Issue by samkristoff** [pycountry/pycountry#200]
The countries.search_fuzzy() function prints match candidates using print().  This pollutes the output making consumer apps harder to debug.

**Comment by zware** [comment]
That's not good :(.  Thanks for the report and patch, @samkristoff!

**Comment by StuartBertram** [comment]
Is there an ETA on when this might be released? Because at the moment it's adding noise to logs, which can be problematic on cloud services and when using otherwise structured logging that you re-parse later for analysis.

**Comment by StuartBertram** [comment]
In case people are still tracking it: Just noticed that this came out in v24.6.1. Thanks!
