### ISSUE TITLE
Yank 23.12.11 from PyPI?

### ISSUE THREAD

**Issue by zware** [pycountry/pycountry#202]
Between #200 and #192, I wonder if we (/our users) wouldn't be better served to yank 23.12.11, clean up the warning situation, and do a new release.

Thoughts, @nschimmoller, @ctheune?

**Comment by ctheune** [comment]
Sorry I dropped the ball on that. I can still yank it if you like...

**Comment by zware** [comment]
It's been long enough that I'm not sure yanking wouldn't be more disruptive now.  On the other hand, I don't know when I'll have a chance to get back in and fix things.

We should do a new release with updated `iso-codes` soon, but I think that's going to take some extra effort this time.
