### ISSUE TITLE
Missing international calling codes

### ISSUE THREAD

**Issue by xeroc** [pycountry/pycountry#216]
Can we have international phone number calling codes added to this lib?

https://en.wikipedia.org/wiki/List_of_country_calling_codes

**Comment by zware** [comment]
All data comes via the upstream Debian `pkg-isocodes` project.  Please see the top two sections of the README: https://github.com/pycountry/pycountry/blob/ea69bab36f00df58624a0e490fdad4ccdc14268b/README.rst?plain=1#L8-L34
