### ISSUE TITLE
Release new version on PyPi

### ISSUE THREAD

**Issue by ddnomad** [pycountry/pycountry#218]
Any chance?

Specifically looking for this because of https://github.com/pycountry/pycountry/commit/482484334ce8ccc33311dd6047619442528b1f82, my use case is very sensitive to superfluous STDOUT output, hence this is a real issue :(

**Comment by zware** [comment]
There are a couple further fixes I want to get into the next release, which I'm hoping to get done soon.

**Comment by zware** [comment]
Did not get everything I wanted into 24.6.1, but did find a few minutes to get it out the door.
