### ISSUE TITLE
Pycountry does not work for Eurostat formatted country codes

### ISSUE THREAD

**Issue by tiborrr** [pycountry/pycountry#224]
In Eurostat databases Greece ISO2 is named the EL instead of GR. Perhaps a Eurostat json could be added, for people who work with Eurostat data.

https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Glossary:Country_codes

**Comment by zware** [comment]
Is there an existing document in a stable location that we could import? Preferably in the Debian `iso-codes` project, which is currently our only data source.

We will not be curating data ourselves here :)

**Comment by tiborrr** [comment]
With regards to the standard, you could make a copy of ISO 3166 alpha-2 and only change Greece. I just found out that Europe has decided it's a good practice to only use Greece as EL and keep the rest according to the ISO3166 standard. Very unusual.

On the official website you can read the following:

the two-letter ISO code should be used ([ISO 3166 alpha-2](https://www.iso.org/obp/ui/#search/code/)), except for Greece, for which the abbreviation EL is recommended;

https://publications.europa.eu/code/en/en-370100.htm

**Comment by tiborrr** [comment]
I agree. Let this ticket be a future reference for others trying to use Eurostat as data source.
