### ISSUE TITLE
Problem with Turkey

### ISSUE THREAD

**Issue by Jaeger87** [pycountry/pycountry#236]
Hi, Turkey name is in original language and not in english:

      "alpha_2": "TR",
      "alpha_3": "TUR",
      "flag": "🇹🇷",
      "name": "Türkiye",
      "numeric": "792",
      "official_name": "Republic of Türkiye"

So, when I'm searching "Turkey" I get a None.

**Comment by estyxx** [comment]
See #148

**Comment by zware** [comment]
Please see our data update policy: https://github.com/pycountry/pycountry?tab=readme-ov-file#data-update-policy

In short, we do not curate data here, but only directly use what is available from the [`iso-codes` project](https://salsa.debian.org/iso-codes-team/iso-codes).

**Comment by Jaeger87** [comment]
Ops sorry, so it is closed?

**Comment by zware** [comment]
Yes, there's nothing to change for this issue in this project.  If you would like to pursue a change in the data, please petition the `iso-codes` project linked in my previous message, and we'll pick up any changes with an update.
