### ISSUE TITLE
Add ccTLD information on Country data

### ISSUE THREAD

**Issue by matheusmatos** [pycountry/pycountry#238]
Hello guys, 

I would love to having TLD (Top Level Domain) information when getting a Country with `pycountry`. For example:

```python
>>> import pycountry
>>> brazil = pycountry.countries.get(alpha_3="BRA")
>>> brazil.tld
".br"
```

I've created a script using Geonames data ([txt file link](http://download.geonames.org/export/dump/countryInfo.txt)), and found only three countries where TLD is different from ISO-3166 (.alpha_2 property):

- BL is different of gp
- GB is different of uk
- MF is different of gp

Despite the small differences, they do exist 😢. If you agree with the idea, I can open a PR. We can do this in two ways:

1. Adapting the `generate.py` to store the data directly into the iso3166-1.json file; or
2. Alternatively, creating a separate `tld_list.json` file and integrating it within the library class.

Thank you,
Matheus Matos

**Comment by matheusmatos** [comment]
Just for information, there's a simple script that can generate the `tld_list.json` file:

```python
import re
import requests
import json

GEONAME_URL = "http://download.geonames.org/export/dump/countryInfo.txt"

response = requests.get(GEONAME_URL)
data = response.text
tld_pattern = re.compile(r"^[a-z]{2}$")

lines = data.split("\n")
country_mapping = {}
for line in lines:
    if not line.startswith("#") and line.strip() != "":
        try:
            columns = line.split("\t")
            iso = columns[0]
            tld = columns[9]
            if tld_pattern.match(tld):
                country_mapping[iso] = tld
        except IndexError:
            pass

with open("cctld_list.json", "w", encoding="utf-8") as f:
    json.dump(country_mapping, f, indent=2, ensure_ascii=False)

```

**Comment by chemelli74** [comment]
Would be amazing to have also this info in the library.
Hope you can consider the request.

**Comment by zware** [comment]
Unfortunately this is rather beyond the scope of this library; we're really just providing a Python API around Debian's `pkg-isocodes` data.  If the requested data was available there we'd be happy to expose it here, but I would rather not add a second source or curate new data ourselves.

Thanks for the suggestion, but I'm afraid we're going to pass on this.
