### ISSUE TITLE
Maputo City (MZ-MPM) does not have parent Maputo Province (MZ-L)

### ISSUE THREAD

**Issue by afizzycola** [pycountry/pycountry#250]
The [MZ-MPM object](https://github.com/pycountry/pycountry/blob/494a4b4c3c567650b877acd808b7ed60af0063cd/src/pycountry/databases/iso3166-2.json#L17690C1-L17694C7) needs ```"parent": "MZ-L"```

**Comment by zware** [comment]
Thanks for the report, but as mentioned in our [data update policy](https://github.com/pycountry/pycountry?tab=readme-ov-file#data-update-policy), changes like this are not accepted here.  Please report the issue [upstream](https://salsa.debian.org/iso-codes-team/iso-codes/-/issues) instead.
