### ISSUE TITLE
currency to country relationship

### ISSUE THREAD

**Issue by rootRaider** [pycountry/pycountry#27]
Hello,

I am proposing a new feature that I have a solution for (unless this exists already, please let me know). 

I am using `country` objects from the `pycountry` library. I then need to look up the official `currency` for this by `country`. I see that `pycountry` has `currency` objects. 

I am proposing the following:
* build a relationship between `country` and `currency` (backed by ISO)
* I will create a `search for currency by country` method somewhere. This method can either be a member of `country` (`country.get_official_currency`) or can just be a utility that can search for the official currency by passing a `country` object as a parameter. I already have data set configured from ISO. I am open to either way of implementation (what ever you think is best for the existing implementation). I already have the basic prototype working for either use case.

I would be more than happy to open a PR and contribute this.

Thanks,

JR

**Comment by rootRaider** [comment]
excel file found from this page (ISO SITE), to map currencies to country.
https://www.iso.org/iso-4217-currency-codes.html

**Comment by rootRaider** [comment]
@ctheune 
hello do you have any interest in this?

**Comment by dennisvd** [comment]
Well I would interested 😀
@ctheune happy to help to implement this is there is interest

**Comment by dennisvd** [comment]
> excel file found from this page (ISO SITE), to map currencies to country.
> https://www.iso.org/iso-4217-currency-codes.html

FYI this list does not include the country code only the country name @rootRaider do you have a list that includes the country code and corresponding currency code?

**Comment by ctheune** [comment]
I general I'm open to this, however, I'd need a reliable source that can be automatically updated without too much fuzzing. 
It might be OK to use: https://www.currency-iso.org/dam/downloads/lists/list_one.xml

About the locale: I think you can lookup data in the locale databases without setting the process-wide locale. I guess using a separate database like pycountry to do this could be helpful to avoid system-dependencies that might have a different release schedule than your application. I'm open to help you guys move this forward, but won't have time to invest in this at the moment.

**Comment by jbaehne** [comment]
I was just looking for this feature and I would love to contribute if not one else can find time.

**Comment by SilverStrings024** [comment]
Has this been implemented yet? I need to use this feature as well, let me know if any help is needed!

**Comment by nschimmoller** [comment]
@SilverStrings024 @jbaehne @dennisvd I believe if you are looking to map a country to it's currency the best package for that currently is [countryinfo](https://pypi.org/project/countryinfo/)
