### ISSUE TITLE
Add numeric key to languages database

### ISSUE THREAD

**Issue by haluunn** [pycountry/pycountry#44]
Hi,

I am trying to get the language name of a country corresponding to the country name or the country code. However, there is no key for me to look up in the languages database. I believe having 'numeric' value there can help. In case a country speaks multiple languages, can add a new attribute such as 'language_order'?

Thank you very much for the package.

**Comment by nschimmoller** [comment]
@haluunn I am going to close out this Issue as it is very old but if you'd like to still have this considered please submit a new issue. If you could provide more details that would be great. 

> I am trying to get the language name of a country corresponding to the country name or the country code

Could you write a few user stories such as "If I looked up United States I'd expect to see _________". As it is written I am unclear on if you are looking for the language the country speaks, in this case primarily English. Alternatively, you may be requesting the name of the country in the local language such as Deutschland for Germany
