### ISSUE TITLE
Support 5 char language codes

### ISSUE THREAD

**Issue by obsidianforensics** [pycountry/pycountry#46]
It would be great if we could use the 5-char language codes for name lookups in the same way as the alpha_2 and alpha_3 codes, something like:

\>\>\>  gb = pycountry.languages.get(alpha_5='en-GB')
\>\>\>  gb.name
English (United Kingdom)

**Comment by nschimmoller** [comment]
@obsidianforensics 'en-GB' is a locale as opposed to a language. Best package I've found for using these is [babel](https://babel.pocoo.org/en/latest/)
