### ISSUE TITLE
Support returning first result from fuzzy search instead of array of results

### ISSUE THREAD

**Issue by sonercirit** [pycountry/pycountry#55]
I think pycountry should have a new method for returning the first result from fuzzy search instead of executing all the conditions all the time.

The execution time and speed would be faster for large data sets.

I can do this if you're interested.

**Comment by ctheune** [comment]
Yeah, that sounds like a good idea. However, fuzzy search has a ranking mechanism where first isn't immediately known, so I'm not sure how that would work (or rather, I have the impression this won't work).
