### ISSUE TITLE
Subdivision lookup fails if item has multiple names

### ISSUE THREAD

**Issue by jac32** [pycountry/pycountry#59]
Hello, thanks for your work on this project. 

I encountered this while doing a lookup by name for subdivision `Wales (GB-WLS)`. 
The subdivision is present in the database but has the name `Wales; Cymru`.

Should the alternative names perhaps be stored in other fields?

**Comment by js-9** [comment]
I am pretty perplexed but actually, with the current version, there seems to be no wales at all!:
```
>>> import pycountry
>>> for region in list(pycountry.subdivisions):
...     if "Wales".lower() in region.name.lower() or "WLS" in region.code.upper():
...             print(region.code, region.name)
... 
AU-NSW New South Wales
```
My version:
```
# dnf info python3-pycountry |grep -E '(Version|Release)'
Version      : 22.3.5
Release      : 1.fc36
```
I wonder wheter this can be because of a database of my distribution? Or is the database included in pycountry?
