### ISSUE TITLE
Missing translations of Cabo Verde, Czechia, North Macedonia, Eswatini for Russian language

### ISSUE THREAD

**Issue by reprintsev** [pycountry/pycountry#65]
`Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32`

```python
>>> pycountry.__version__
'20.7.3'
```

```python
>>> import pycountry
>>> import gettext
>>> locale_ru = gettext.translation('iso3166', pycountry.LOCALES_DIR, languages=['RU'])
>>> for c in ['CV', 'CZ', 'MK', 'SZ']:
	co = pycountry.countries.get(alpha_2=c)
	locale_ru.gettext(co.name)

'Cabo Verde'
'Czechia'
'North Macedonia'
'Eswatini'
```

At the same time, translations for these countries are present in the file `pycountry\locales\ru\LC_MESSAGES\iso3166-1.mo`:
```
Кабо-Верде
Чехия
Северная Македония
Эсватини
```

Translations:

English|Russian
-------|---------
Cabo Verde|Кабо-Верде
Czechia|Чехия
North Macedonia|Северная Македония
Eswatini|Эсватини

**Comment by nschimmoller** [comment]
@reprintsev all data and translations come from [Debian](https://salsa.debian.org/iso-codes-team/iso-codes) per our data update policy

> Data update policy
> No changes to the data will be accepted into pycountry. This is a pure wrapper around the ISO standard using the pkg-isocodes database from Debian as is. If you need changes to the political situation in the world, please talk to the ISO or Debian people

You can contribute to translation services [here](https://hosted.weblate.org/projects/iso-codes/)
