### ISSUE TITLE
United Kingdom - Great Britain - shorthand request

### ISSUE THREAD

**Issue by Velocitractor00** [pycountry/pycountry#67]
Hi, this is a really minor thing on the grand scheme of it, but we have users setting their country through our discord bot (which uses your library) - we have noticed that when people type "UK" it is partial matching this to Ukraine, and not (what they expect) as the United Kingdom - I noticed in your fuzzy code you have slots for GB and GBR but honestly, it would make much more sense to have UK instead or as well as GBR - I am sure its a used shorthand outside of the UK, but most people here refer to them differently 

as GB doesn't include Northern Ireland 

a humble request to include UK (if its cap sensitive even better) as the fuzzy code or alpha for United Kindgom 

thanks 

appreciate all your work 

G

**Comment by vincentborghi** [comment]
+1

**Comment by camin-mccluskey** [comment]
+1

**Comment by nschimmoller** [comment]
@Velocitractor00 per our data update policy 

> Data update policy
> No changes to the data will be accepted into pycountry. This is a pure wrapper around the ISO standard using the pkg-isocodes database from Debian as is. If you need changes to the political situation in the world, please talk to the ISO or Debian people. 

Good update though is that in main due to #175 there is now the ability to add and remove entries in the countries class. 

``` python
>>> pycountry.countries.add_entry(alpha_2="XK", alpha_3="XXK", name="Kosovo", numeric="926")
>>> pycountry.countries.remove_entry(alpha_2="XK")
``` 

You could use this to remove Ukraine or add a record for the UK to fit your specific use case. Will be looking at another pypi release soon.
