### ISSUE TITLE
Request for sub-continental code

### ISSUE THREAD

**Issue by HariWu1995** [pycountry/pycountry#76]
Dear team,

I need a little more specific info from continent code. For example, America has North and South for now, but it's better if it also has Central; Asia and Europe are large, they should be divided into sub-continents.
Some links you can refer to are 
- https://www.geodatasource.com/resources/tutorials/what-are-the-continent-subcontinent-supported/
- https://cies2018.org/wp-content/uploads/List-of-Countries-by-Region-UN-Annex-II.pdf

**Comment by blairnangle** [comment]
@HariWu1995 how are you able to access continent code?

From what I can see, it's not available on in the JSON "databases" or the API.

**Comment by HariWu1995** [comment]
@blairnangle I am submitting a request, I don't share a solution yet

**Comment by nschimmoller** [comment]
@HariWu1995 this library is only a wrapper for ISO Standards. Is there a specific ISO standard you're hoping for? If so please open a new Issue specifying that request. I'll be closing this out as it is stale and likely not in scope for the library.
