### ISSUE TITLE
Feature Request: Vehicle Registration Codes

### ISSUE THREAD

**Issue by lambdaTotoro** [pycountry/pycountry#77]
In my application, users tend to also enter their nationalities in Vehicle Registration Codes (for some reason).
Examples are "H" for Hungary, "Q" for Qatar or "WAN" for (West Africa) Nigeria.

https://en.wikipedia.org/wiki/International_vehicle_registration_code#Current_codes

It would be lovely to be able to lookup country objects by IVRC as well.

**Comment by Kreusada** [comment]
This sounds great, if this is agreed with I'd love to be assigned to this.
