### ISSUE TITLE
Add mapping between countries to their iso languages

### ISSUE THREAD

**Issue by moshewe** [pycountry/pycountry#80]
There is no way to link a country to the language spoken in it using the library only as it's written right now. 
Solutions exist, E.g.:
https://stackoverflow.com/questions/2680619/match-language-code-with-countries-where-this-language-is-an-official-or-commonl
https://stackoverflow.com/questions/32773035/list-of-language-codes-iso639-1-in-python

Getting from a country to its languages will provide a consistent usage experience, just like with subdivisions and currencies.

**Comment by nschimmoller** [comment]
@moshewe please see my comment on #101
