### ISSUE TITLE
[Question] How to lookup for entire Column?

### ISSUE THREAD

**Issue by miriam-z** [pycountry/pycountry#82]
Using pandera schema validation:
 
```
import pandera as pa
 
schema = pa.DataFrameSchema({

    "Country" : pa.Column(pycountry.countries.lookup('fr'), required=True), // Lookup entire Column for validate country names
    "Currency" : pa.Column(pycountry.currencies.lookup('usd'), required=True), // Lookup entire Column for validate currencies

})
//Validating the data
schema.validate(data_sample)
```

**Comment by MaxGhenis** [comment]
I'm not familiar with `pandera` and not clear exactly on your question, but you can lookup a column in `pandas` with list comprehension or vectorization:
```
df = pd.DataFrame(dict(code=["FR", "US"]))

[pycountry.countries.lookup(x).name for x in df.code]
# ['France', 'United States']
```
or
```
df.code.apply(lambda x: pycountry.countries.lookup(x).name)
# 0           France
# 1    United States
# Name: code, dtype: object
```

**Comment by ctheune** [comment]
Actually, @miriam-z your example is a bit confusing. Do you want lookup('fr') to return multiple lines for everything that lookup considers a match instead of a single line? This would be different than from what @MaxGhenis is suggesting, but I'm not sure based on your example ...
