### ISSUE TITLE
Get alpha_2 with alpha_3

### ISSUE THREAD

**Issue by glosophy** [pycountry/pycountry#98]
I currently have countries with their corresponding ISO3 code. How can I look up countries' ISO2 code with the ISO3?

**Comment by benelgiac** [comment]
what about getting the language via alpha_2 and then reading the alpha_3 attribute?

```
>> pycountry.languages.get(alpha_3='eng').alpha_2
'en'
```

**Comment by nschimmoller** [comment]
@glosophy please see below code @benelgiac it is even easier than that. 

``` python
>>> import pycountry
>>> alpha_3 = 'USA'
>>> country = pycountry.countries.get(alpha_3=alpha_3)
>>> country.alpha_2
'US'
```
