### ISSUE TITLE
Unclear/illegal copyright

### ISSUE THREAD

**Issue by Natureshadow** [pycountry/pycountry#99]
The copyright information on the project is unclear, or in other words: The copyright information is clearly wrong because it is illegal.

German companies cannnot hold copyright on anything. Only indiiduals can be copyright holders under German law.

In order to make the licence and copyright clear and allow legal use and forking (which requires stating the original copyright holders correctly), please list the individuals holding the copyright.

**Comment by ctheune** [comment]
Argh. So for some reason this never appeared to me but first review seems you're right. I guess I "grew up" too much in the US-centric open source community and just have been doing it this way. Guess I'll have to brush things up again... le sigh.

**Comment by ctheune** [comment]
Notes from a call with @nschimmoller

* LGPL requires copyright notices.
* I _think_ we want to put that in a separate COPYRIGHT.txt and also make clear that the embedded data files are exempt from this.
* We should brush up on best practices how to handle "random internet person" contributions correctly. I'm on a very liberal side here as we will never relicense in the future and so we can just freely accept stuff and I'd be happy to also attribute people in the copyright file.
* We need to go through all committers and aggregate the indivual names into the COPYRIGHT.txt
* We need to keep this up to date in the future.

**Comment by ctheune** [comment]
@nschimmoller I think you wanted to take a look at this. 

Also @Natureshadow are you up to date on best practices with a liberal perspective here? Can we chat about this face to face maybe?

**Comment by Natureshadow** [comment]
Hi,

> Also @Natureshadow are you up to date on best practices with a liberal perspective here? Can we chat about this face to face maybe?

We can do that, after I return from vaccation next Wednesday.

**Comment by ctheune** [comment]
Sounds great. Enjoy your vacation!

**Comment by Natureshadow** [comment]
So, I am back. @ctheune any proposals on when to talk?

The first step would be to determine which parts of the code must be considered copyrightable work in the first place. I assume this will simplify things quite a lot.

**Comment by nschimmoller** [comment]
@ctheune @Natureshadow 

I have created a Pull Request #181 that should address these issues. Gathering the contributors was somewhat annoying but can be done through a combination of the following two git commands

- Used to retrieve all contributors with two (first & last names)
``` git 
git log --format='%aN %aI' | awk '{print substr($0, 1, index($0,$3)-2) " " substr($3, 1, 4)}' | sort -u
```
- Used to retrieve all contributors with three (first, middle & last names)
``` git
git log --format='%aN %aI' | awk -F ' 20' '{print $1 " 20"$2}' | awk '{print $1, $2, $3 " " substr($4, 1, 4)}' | sort -u
```

**Comment by zware** [comment]
I believe this has been addressed.  Please let me know if things still aren't right.
